//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VentEvaluate.rc
//
#define IDC_EVAL_DO_BTN                 3
#define IDS_PROJNAME                    100
#define IDC_CYCLE_LIST                  100
#define IDC_CYCLE_UPDATE_BTN            101
#define IDD_CYCLE_LIST_DLG              102
#define IDC_CC_LIST_UPDATE_BTN          103
#define IDD_VENT_SHAFT_LIST_DLG         104
#define IDC_CC_LIST                     104
#define IDD_SIMPLE_INPUT_DLG            105
#define IDC_VENT_SHAFT_UPDATE_BTN       105
#define IDD_SHAFT_EXTRA_INFO_DLG        106
#define IDC_VENT_SHAFT_LIST             106
#define IDC_VENT_SHAFT_PARAM_BTN        109
#define IDD_MINE_INFO_DLG               111
#define IDD_PROJECT_INFO_DLG            112
#define IDD_TUNNEL_TYPE_DLG             114
#define IDD_TUNNEL_PARAM_DLG            114
#define IDC_INPUT_STR_EDIT              115
#define IDD_WS_AIR_FLOW_PARAM_DLG       116
#define IDD_WS_PARAM_DLG                116
#define IDD_TWS_AIR_FLOW_PARAM_DLG      117
#define IDD_TWS_PARAM_DLG               117
#define IDD_ROOM_PARAM_DLG              118
#define IDC_LIFT_MATERIAL_RADIO         119
#define IDC_LIFT_COAL_RADIO             120
#define IDC_GLADER_CHECK                121
#define IDC_STUFF_CHECK                 122
#define IDD_WIND_STATION_DLG            122
#define IDC_MATERIAL_CHECK              123
#define IDD_INSTRUMENT_DLG              123
#define IDC_SKIP_HOIST_RADIO            124
#define IDC_BELT_CONVEY_RADIO           125
#define IDC_ENCLOSE_CHECK               126
#define IDD_EVAL_DLG                    126
#define IDC_DUST_PROOF_CHECK            127
#define IDD_CC_LIST_DLG                 127
#define IDC_CH4_CHECK                   128
#define IDD_DIESEL_PARAM_DLG            128
#define IDC_FIRE_ALARM_CHECK            129
#define IDD_MACHINE_ROOM_DLG            129
#define IDC_PIPE_CHECK                  130
#define IDD_CHARGE_DLG                  130
#define IDD_POWDER_DLG                  131
#define IDC_NO_USE_RADIO                132
#define IDC_MINE_NAME                   132
#define IDD_HELP_DLG                    132
#define IDC_MINE_COMPANY                133
#define IDD_QuestionNaire_DLG           133
#define IDC_MINE_DESIGN_DATE            134
#define IDD_AIR_COMPOSITION_DLG         134
#define IDC_MINE_QUALITY                136
#define IDD_WS_AIR_FLOW_DLG             136
#define IDC_MINE_GAS_LEVEL              137
#define IDD_MC_DLG                      137
#define IDC_MINE_WORK_DATE              138
#define IDC_PROJECT_EVAL_BASIS          138
#define IDD_GAS_DLG                     138
#define IDR_HTML_EVALDLG                139
#define IDD_MPNW_DLG                    139
#define IDC_MINE_VENT                   140
#define IDD_AFC_DLG                     140
#define IDD_TWS_AIR_FLOW_DLG            141
#define IDD_LOCAL_FAN_DLG               142
#define IDD_OT_AIR_FLOW_DLG             143
#define IDD_DHC_AIR_FLOW_DLG            144
#define IDD_GE_LIST_DLG                 145
#define IDD_DATA_LIST_DLG               145
#define IDC_TUNNEL_TYPE_NEED_AIR        148
#define IDC_TUNNEL_TYPE_LIST            149
#define IDC_DATETIMEPICKER1             150
#define IDC_DATETIMEPICKER2             151
#define IDC_DATETIMEPICKER3             152
#define IDC_DATETIMEPICKER4             153
#define IDC_DATETIMEPICKER5             154
#define IDC_TUNNEL_TYPE_BTN             154
#define IDC_DATETIMEPICKER6             155
#define IDC_TUNNEL_TYPE_SEL_BTN         155
#define IDC_DATETIMEPICKER7             156
#define IDC_DATETIMEPICKER8             157
#define IDC_AIR_FLOW_WS_LIST            157
#define IDC_AIR_FLOW_WS_POS             158
#define IDC_AIR_FLOW_WS_BTN             159
#define IDC_AIR_FLOW_WS_SEL_BTN         160
#define IDC_AIR_FLOW_TWS_POS            161
#define IDC_DATETIMEPICKER13            162
#define IDC_AIR_FLOW_TWS_BTN            162
#define IDC_DATETIMEPICKER14            163
#define IDC_AIR_FLOW_TWS_SEL_BTN        163
#define IDC_DATETIMEPICKER15            164
#define IDC_AIR_FLOW_TWS_LIST           164
#define IDC_DATETIMEPICKER16            165
#define IDC_AIR_FLOW_POWDER_LIST        165
#define IDC_AIR_FLOW_POWDER_BTN         166
#define IDC_AIR_FLOW_POWDER_SEL_BTN     167
#define IDC_AIR_FLOW_POWDER_VOLUM       168
#define IDC_POWDER_VOLUM                168
#define IDC_AIR_FLOW_CHARGE_H2          172
#define IDC_CHARGE_CHARGE_H2            172
#define IDC_CHARGE_H2                   172
#define IDC_MACHINE_POWER               176
#define IDC_MACHINE_TEMPERATURE         177
#define IDC_MACHINE_SLIDER1             179
#define IDC_MACHINE_RADIO1              180
#define IDC_MACHINE_RADIO2              181
#define IDC_MACHINE_RADIO4              182
#define IDC_MACHINE_RADIO3              183
#define IDC_HOT_COEFF1                  185
#define IDC_WIND_STATION_UPDATE_BTN     199
#define IDC_WIND_STATION_SEL_BTN        200
#define IDC_WIND_STATION_CHECK1         201
#define IDC_WIND_STATION_CHECK2         202
#define IDC_WIND_STATION_LIST           203
#define IDC_WIND_STATION_REASON         204
#define IDC_INSTRUMENT_LIST             205
#define IDC_INSTRUMENT_NUM              206
#define IDC_INSTRUMENT_TYPE             207
#define IDC_INSTRUMENT_INSTITUTE        208
#define IDC_INSTRUMENT_FACTORY          209
#define IDC_INSTRUMENT_RADIO1           210
#define IDC_INSTRUMENT_RADIO2           211
#define IDC_START_ZLEVEL                215
#define IDC_END_ZLEVEL                  216
#define IDC_GAS_DANGEROUS               217
#define IDC_EVAL_DB_TEMPLATE_PATH       223
#define IDC_EVAL_DB_TEMPLATE_PATH_SEL_BUTTON 224
#define IDC_EVAL_REGULATION_LIST        225
#define IDC_EVAL_OUTPUT_BUTTON          226
#define IDC_EVAL_OUTPUT_EDIT            227
#define IDC_TUNNEL_TYPE_RADIO6          228
#define IDC_TUNNEL_TYPE_RADIO7          229
#define IDC_MINE_INFO_SLIDER1           230
#define IDC_MINE_INFO_SLIDER2           231
#define IDC_MINE_INFO_COEFF1            232
#define IDC_MINE_INFO_COEFF2            233
#define IDC_TOTAL_Q                     234
#define IDC_INSTRUMENT_ADD_BTN          235
#define IDC_STATION_AREA                235
#define IDC_INSTRUMENT_DEL_BTN          236
#define IDC_STATION_VELOCITY            236
#define IDC_STATION_Q                   237
#define IDC_TUNNEL_TYPE_DIESEL_PARAM_BTN 240
#define IDC_DIESEL_PARAM_NUM            241
#define IDC_DIESEL_PARAM_POWER          242
#define IDC_TUNNEL_AREA_EDIT            243
#define IDC_TUNNEL_CH4_EDIT             244
#define IDC_TUNNEL_MATERIAL_TYPE        245
#define IDC_TUNNEL_NAME_EDIT            246
#define IDC_TUNNEL_VELOCITY_EDIT        247
#define IDC_TUNNEL_TEMP_EDIT            248
#define IDC_SHAFT_NAME_EDIT             249
#define IDC_ROOM_Q_EDIT                 249
#define IDC_TUNNEL_Q_EDIT               249
#define IDC_SHAFT_AREA_EDIT             250
#define IDC_ROOM_VELOCITY_EDIT          250
#define IDC_SHAFT_VELOCITY_EDIT         251
#define IDC_ROOM_AREA_EDIT              251
#define IDC_SHAFT_TEMP_EDIT             252
#define IDC_WS_TEMP_MEASURE_RADIO1      253
#define IDC_WS_TEMP_MEASURE_RADIO2      254
#define IDC_WS_TEMP_MEASURE_RADIO3      255
#define IDC_TWS_TUNNEL_MATERIAL_TYPE    256
#define IDC_TWS_TEMP_MEASURE_RADIO1     257
#define IDC_TWS_TEMP_MEASURE_RADIO2     258
#define IDC_TWS_TEMP_MEASURE_RADIO3     259
#define IDC_ROOM_NAME_EDIT              260
#define IDC_ROOM_TEMP_EDIT              261
#define IDC_ROOM_TEMP_MEASURE_RADIO1    262
#define IDC_ROOM_TEMP_MEASURE_RADIO2    263
#define IDC_ROOM_TEMP_MEASURE_RADIO3    264
#define IDC_STATION_READ_BTN            265
#define IDC_STATION_NAME                266
#define IDC_STATION_ZOOM_BTN            267
#define IDC_TUNNEL_FUNC_TYPE            268
#define IDC_PREVIOUS_BTN                269
#define IDC_EXTRA_ROOM_PARAM_POS        272
#define IDC_CLAUSE_CONTENT              273
#define IDC_YES_RADIO                   274
#define IDC_NO_RADIO                    275
#define IDC_NEXT_BTN                    276
#define IDC_CONTENT_RECT_STATIC         277
#define IDC_TUNNEL_ALLOCATE_Q_EDIT      278
#define IDC_AIR_O2_EDIT                 279
#define IDC_AIR_CO2_EDIT                280
#define IDC_AIR_CO_EDIT                 281
#define IDC_AIR_NO_EDIT                 282
#define IDC_AIR_SO2_EDIT                283
#define IDC_AIR_H2S_EDIT                284
#define IDC_AIR_NH3_EDIT                285
#define IDC_MC_LENGTH_EDIT              288
#define IDC_MC_MIN_KDJ_EDIT             289
#define IDC_GAS_Q_CH4_EDIT              289
#define IDC_MC_MAX_KDJ_EDIT             290
#define IDC_GAS_K_CH4_EDIT              290
#define IDC_MPN_EDIT                    290
#define IDC_MC_HEIGHT_EDIT              291
#define IDC_GAS_Q_CH4_TAIL_EDIT         291
#define IDC_MW_EDIT                     291
#define IDC_WS_AFC_MC_BTN               291
#define IDC_MC_k_HEIGHT_EDIT            292
#define IDC_TWS_AFC_GAS_BTN             292
#define IDC_MC_K_LENGTH_EDIT            293
#define IDC_WS_AFC_MPNW_BTN             293
#define IDC_TWS_AFC_LOCAL_FAN_BTN       293
#define IDC_MC_K_TEMP_EDIT              294
#define IDC_IN_HIGH_GAS                 294
#define IDC_TWS_AFC_MPNW_BTN            294
#define IDC_MC_VELOCITY_EDIT            295
#define IDC_WS_NAME_EDIT                295
#define IDC_WS_AREA_EDIT                296
#define IDC_WS_VELOCITY_EDIT            297
#define IDC_WS_TEMP_EDIT                298
#define IDC_TWS_AIR_COMPOSITION_BTN     299
#define IDC_WS_Q_EDIT                   299
#define IDC_AFC_BTN                     300
#define IDC_AFC_USER_ALLOCATE_Q_CHECK   301
#define IDC_AFC_ALLOCATE_Q_EDIT         302
#define IDC_WS_AFC_GAS_BTN              305
#define IDC_LOCAL_FAN_NUM_EDIT          306
#define IDC_LOCAL_FAN_Q_EDIT            307
#define IDC_TWS_NAME_EDIT               308
#define IDC_TWS_AREA_EDIT               309
#define IDC_TWS_VELOCITY_EDIT           310
#define IDC_TWS_TEMP_EDIT               311
#define IDC_WS_AIR_COMPOSITION_BTN      312
#define IDC_TWS_VELOCITY_EDIT2          312
#define IDC_TWS_Q_EDIT                  312
#define IDC_WS_AFC_BTN                  313
#define IDC_TWS_AFC_BTN                 314
#define IDC_OT_AFC_BTN                  315
#define IDC_OT_AFC_GAS_BTN              316
#define IDC_OT_AFC_DIESEL_BTN           317
#define IDC_ROOM_OTHER_PARAM_BTN        320
#define IDC_ROOM_AFC_BTN                321
#define IDC_DHC_AFC_POWDER_BTN          322
#define IDC_DHC_AFC_CHARGE_BTN          323
#define IDC_DHC_AFC_MACHINE_BTN         324
#define IDC_TYPE_LIST                   324
#define IDC_UPDATE_BTN                  325
#define IDC_DATA_LIST_UPDATE_BTN        325
#define IDC_GE_LIST                     326
#define IDC_DATA_LIST                   326
#define IDC_BUTTON1                     328
#define IDC_DATA_LIST_HILIGHT_SELECT_BTN 328

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         329
#define _APS_NEXT_SYMED_VALUE           140
#endif
#endif
