######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 17:27:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += sql

# Input
HEADERS += canshuDialog.h mainDialog.h
SOURCES += canshuDialog.cpp main.cpp mainDialog.cpp
#TRANSLATIONS=dialog_zh.ts
